/**
 * Alerts page title header.
 */

import { Plus } from 'lucide-react'

export default function AlertsHeader() {
  return (
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
      <div>
        <h2 className="text-2xl font-semibold tracking-tight text-gray-900">Alerts</h2>
        <p className="mt-1 max-w-2xl text-sm text-gray-500">
          Monitor alerts generated by your services and infrastructure.
        </p>
      </div>

      <button
        type="button"
        className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-pulse-600 px-4 py-2 text-sm font-medium text-white shadow-sm transition-colors hover:bg-pulse-700"
      >
        <Plus className="size-4" aria-hidden="true" />
        Create Alert Rule
      </button>
    </div>
  )
}
