/**
 * Slide-over panel showing report metadata and preview.
 */

import { Download, FileText, X } from 'lucide-react'

import type { Report } from '../../types/report.ts'
import type { User } from '../../types/user.ts'
import {
  formatDateRange,
  formatDateTime,
  formatRelativeTime,
  getInitials,
} from '../../lib/format.ts'
import { reportTypeLabels } from '../../types/report.ts'
import ReportStatusBadge from './ReportStatusBadge.tsx'

interface ReportDetailsProps {
  report: Report | null
  author?: User
  onClose: () => void
  onDownload: (report: Report) => void
}

export default function ReportDetails({
  report,
  author,
  onClose,
  onDownload,
}: ReportDetailsProps) {
  if (!report) {
    return null
  }

  return (
    <>
      <button
        type="button"
        aria-label="Close report details"
        className="fixed inset-0 z-40 bg-black/40"
        onClick={onClose}
      />

      <aside className="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col border-l border-gray-200 bg-white shadow-xl">
        <div className="flex items-start justify-between border-b border-gray-100 px-5 py-4">
          <div className="flex items-start gap-3">
            <div className="flex size-10 items-center justify-center rounded-lg bg-gray-100 text-gray-600">
              <FileText className="size-5" aria-hidden="true" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-900">{report.name}</h3>
              <div className="mt-1">
                <ReportStatusBadge status={report.status} />
              </div>
            </div>
          </div>
          <button
            type="button"
            aria-label="Close panel"
            className="rounded-lg p-1.5 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600"
            onClick={onClose}
          >
            <X className="size-5" aria-hidden="true" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-5 py-5">
          <p className="text-sm leading-relaxed text-gray-600">{report.summary}</p>

          {report.description && (
            <p className="mt-3 text-sm text-gray-500">{report.description}</p>
          )}

          <div className="mt-6 grid grid-cols-2 gap-4">
            <DetailStat label="Type" value={reportTypeLabels[report.type]} />
            <DetailStat label="Scope" value={report.scope} />
            <DetailStat
              label="Period"
              value={formatDateRange(report.periodStart, report.periodEnd)}
            />
            <DetailStat
              label="Created"
              value={formatRelativeTime(report.createdAt)}
              subtext={formatDateTime(report.createdAt)}
            />
            <DetailStat label="Generated By" value={author?.name ?? 'Unknown'} />
            {report.scheduledFor && (
              <DetailStat
                label="Scheduled For"
                value={formatDateTime(report.scheduledFor)}
              />
            )}
          </div>

          <section className="mt-8">
            <h4 className="text-sm font-semibold text-gray-900">Key Metrics</h4>
            <div className="mt-3 space-y-2">
              {report.metrics.map((metric) => (
                <div
                  key={metric.label}
                  className="flex items-center justify-between rounded-lg border border-gray-100 bg-gray-50/50 px-3 py-2.5"
                >
                  <span className="text-sm text-gray-600">{metric.label}</span>
                  <span className="text-sm font-medium text-gray-900">{metric.value}</span>
                </div>
              ))}
            </div>
          </section>
        </div>

        <div className="border-t border-gray-100 px-5 py-4">
          <button
            type="button"
            onClick={() => onDownload(report)}
            className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-pulse-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-pulse-700"
          >
            <Download className="size-4" aria-hidden="true" />
            Export Report
          </button>
          {author && (
            <div className="mt-3 flex items-center gap-2">
              <div className="flex size-8 items-center justify-center rounded-full bg-pulse-100 text-xs font-semibold text-pulse-700">
                {getInitials(author.name)}
              </div>
              <div>
                <p className="text-sm font-medium text-gray-900">{author.name}</p>
                <p className="text-xs text-gray-500">{author.email}</p>
              </div>
            </div>
          )}
        </div>
      </aside>
    </>
  )
}

function DetailStat({
  label,
  value,
  subtext,
}: {
  label: string
  value: string
  subtext?: string
}) {
  return (
    <div className="rounded-lg border border-gray-100 bg-gray-50/50 px-3 py-2.5">
      <p className="text-xs font-medium text-gray-500">{label}</p>
      <p className="mt-0.5 text-sm font-semibold text-gray-900">{value}</p>
      {subtext && <p className="mt-0.5 text-xs text-gray-400">{subtext}</p>}
    </div>
  )
}
