/**
 * Table of reports with view, download, and delete actions.
 */

import { Inbox, SearchX } from 'lucide-react'

import type { Report } from '../../types/report.ts'
import type { User } from '../../types/user.ts'
import Card from '../ui/Card.tsx'
import ReportRow, { ReportMobileCard } from './ReportRow.tsx'

interface ReportsTableProps {
  reports: Report[]
  totalCount: number
  users: User[]
  onView: (report: Report) => void
  onDownload: (report: Report) => void
  onDelete: (report: Report) => void
}

export default function ReportsTable({
  reports,
  totalCount,
  users,
  onView,
  onDownload,
  onDelete,
}: ReportsTableProps) {
  const getUserById = (id: string) => users.find((user) => user.id === id)
  const hasNoReports = totalCount === 0
  const hasNoMatches = !hasNoReports && reports.length === 0

  return (
    <Card>
      <div className="border-b border-gray-100 px-5 py-4">
        <h3 className="text-base font-semibold text-gray-900">
          All Reports
          <span className="ml-2 text-sm font-normal text-gray-500">({reports.length})</span>
        </h3>
      </div>

      {reports.length > 0 ? (
        <>
          <div className="hidden overflow-x-auto lg:block">
            <table className="w-full min-w-[900px]">
              <thead>
                <tr className="border-b border-gray-100 text-left text-xs font-medium uppercase tracking-wide text-gray-500">
                  <th className="px-5 py-3 font-medium">Report</th>
                  <th className="hidden py-3 pr-4 font-medium md:table-cell">Type</th>
                  <th className="hidden py-3 pr-4 font-medium lg:table-cell">Period</th>
                  <th className="hidden py-3 pr-4 font-medium sm:table-cell">Created</th>
                  <th className="py-3 pr-4 font-medium">Status</th>
                  <th className="hidden py-3 pr-4 font-medium lg:table-cell">Generated By</th>
                  <th className="px-5 py-3 font-medium">
                    <span className="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {reports.map((report) => (
                  <ReportRow
                    key={report.id}
                    report={report}
                    author={getUserById(report.generatedById)}
                    onView={onView}
                    onDownload={onDownload}
                    onDelete={onDelete}
                  />
                ))}
              </tbody>
            </table>
          </div>

          <div className="flex flex-col gap-3 p-4 lg:hidden">
            {reports.map((report) => (
              <ReportMobileCard
                key={report.id}
                report={report}
                author={getUserById(report.generatedById)}
                onView={onView}
                onDownload={onDownload}
                onDelete={onDelete}
              />
            ))}
          </div>
        </>
      ) : (
        <EmptyState hasNoReports={hasNoReports} hasNoMatches={hasNoMatches} />
      )}
    </Card>
  )
}

function EmptyState({
  hasNoReports,
  hasNoMatches,
}: {
  hasNoReports: boolean
  hasNoMatches: boolean
}) {
  if (hasNoReports) {
    return (
      <div className="flex flex-col items-center px-5 py-16 text-center">
        <div className="flex size-12 items-center justify-center rounded-full bg-gray-100 text-gray-400">
          <Inbox className="size-6" aria-hidden="true" />
        </div>
        <h4 className="mt-4 text-sm font-semibold text-gray-900">No reports yet</h4>
        <p className="mt-1 max-w-sm text-sm text-gray-500">
          Generate your first report to review operational metrics and trends.
        </p>
      </div>
    )
  }

  if (hasNoMatches) {
    return (
      <div className="flex flex-col items-center px-5 py-16 text-center">
        <div className="flex size-12 items-center justify-center rounded-full bg-gray-100 text-gray-400">
          <SearchX className="size-6" aria-hidden="true" />
        </div>
        <h4 className="mt-4 text-sm font-semibold text-gray-900">No matching reports</h4>
        <p className="mt-1 max-w-sm text-sm text-gray-500">
          Try adjusting your search or filters to find what you are looking for.
        </p>
      </div>
    )
  }

  return null
}
